Book_Store/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Book_Store.Controllers
{
	public class BlogController : Controller
	{
		public IActionResult Index() => View();
		
	}
}

Book_Store/Controllers/BooksController.cs
using Book_Store.Models;
using Book_Store.Models.Dtos;
using Book_Store.Repository.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Book_Store.Controllers
{
	public class BooksController : Controller
	{
		private readonly DataContext _db;
        public BooksController(DataContext db)
        {
            _db = db;
        }

		[Route("/books")]
		public IActionResult Index()
		{
			List<Book> listBooks = _db.Books.ToList();
			return View(listBooks);
		}

		public IActionResult Details(int id)
		{
			var books = _db.Books.Include(b => b.Publisher).FirstOrDefault(b => b.Id == id);

			if(books == null)
			{
				return NotFound();
			}

			return View(books);
		}

        public IActionResult BookByPublisher(int id)
        {
            var bookByPublisher = _db.Books.Where(b => b.PublisherId == id).ToList();
            return View(bookByPublisher);
        }

		[Route("/books/ShowBookAPI")]
		public async Task<IActionResult> ShowBookAPI()
		{
			using (var httpClient = new HttpClient())
			{
				string apiUrl = "https://localhost:7245/api/BookAPI/"; 

				try
				{
					HttpResponseMessage response = await httpClient.GetAsync(apiUrl);

					if (response.IsSuccessStatusCode)
					{
						// API call was successful
						string responseData = await response.Content.ReadAsStringAsync();
						List<Book> books = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Book>>(responseData);
						return View(books);
					}
					else
					{
						// Handle unsuccessful API call
						return Redirect("/");
					}
				}
				catch (Exception ex)
				{
					// Handle exception
					Console.WriteLine("An error occurred: " + ex.Message);
					return Redirect("");
				}
			}
		}
	}
}

Book_Store/Controllers/TopicsController.cs
using Book_Store.Models;
using Book_Store.Repository.Data;
using Microsoft.AspNetCore.Mvc;

namespace Book_Store.Controllers
{
	public class TopicsController : Controller
	{
		private readonly DataContext _db;
        public TopicsController(DataContext db)
        {
			_db = db;
        }
		public IActionResult Index()
		{
			List<Topic> listTopics = _db.Topics.ToList();
			return View(listTopics);
		}

		public IActionResult BookByTopics(int id) {
			
			var bookByTopics = _db.Books.Where(b => b.TopicId == id).ToList();
			return View(bookByTopics);
		}
	}
}

Book_Store/Views/Shared/_FooterPartial.cshtml
<footer class="site-footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="widget">
					<h3 class="mb-4">About</h3>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
				</div> <!-- /.widget -->
				<div class="widget">
					<h3>Social</h3>
					<ul class="list-unstyled social">
						<li><a asp-controller="" asp-action=""><span class="icon-instagram"><i class="bi bi-instagram"></i></span></a></li>
						<li><a asp-controller="" asp-action=""><span class="icon-twitter"><i class="bi bi-twitter"></i></span></a></li>
						<li><a asp-controller="" asp-action=""><span class="icon-facebook"><i class="bi bi-facebook"></i></span></a></li>
						<li><a asp-controller="" asp-action=""><span class="icon-linkedin"><i class="bi bi-linkedin"></i></span></a></li>
						<li><a asp-controller="" asp-action=""><span class="icon-pinterest"><i class="bi bi-pinterest"></i></span></a></li>
						<li><a asp-controller="" asp-action=""><span class="icon-dribbble"><i class="bi bi-dribbble"></i></span></a></li>
					</ul>
				</div> <!-- /.widget -->
			</div> <!-- /.col-lg-4 -->
			<div class="col-lg-4 ps-lg-5">
				<div class="widget">
					<h3 class="mb-4">Company</h3>
					<ul class="list-unstyled float-start links">
						<li><a asp-controller="" asp-action="">About us</a></li>
						<li><a asp-controller="" asp-action="">Services</a></li>
						<li><a asp-controller="" asp-action="">Vision</a></li>
						<li><a asp-controller="" asp-action="">Mission</a></li>
						<li><a asp-controller="" asp-action="">Terms</a></li>
						<li><a asp-controller="" asp-action="">Privacy</a></li>
					</ul>
					<ul class="list-unstyled float-start links">
						<li><a asp-controller="" asp-action="">Partners</a></li>
						<li><a asp-controller="" asp-action="">Business</a></li>
						<li><a asp-controller="" asp-action="">Careers</a></li>
						<li><a asp-controller="" asp-action="">Blog</a></li>
						<li><a asp-controller="" asp-action="">FAQ</a></li>
						<li><a asp-controller="" asp-action="">Creative</a></li>
					</ul>
				</div> <!-- /.widget -->
			</div> <!-- /.col-lg-4 -->
			<div class="col-lg-4">
				<div class="widget">
					<h3 class="mb-4">Top Best Book In My Shop</h3>
					<div class="post-entry-footer">
						<ul>
							<vc:top-books></vc:top-books>
						</ul>
					</div>


				</div> <!-- /.widget -->
			</div> <!-- /.col-lg-4 -->
		</div> <!-- /.row -->

		<div class="row mt-5">
			<div class="col-12 text-center">
				<!--
					**==========
					NOTE:
					Please don't remove this copyright link unless you buy the license here https://untree.co/license/
					**==========
				  -->

				<p>Copyright &copy; 2023</p>
			</div>
		</div>
	</div> <!-- /.container -->
</footer> <!-- /.site-footer -->

Book_Store/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Untree.co">
	<link rel="shortcut icon" href="favicon.png">

	<meta name="description" content="" />
	<meta name="keywords" content="bootstrap, bootstrap5" />

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600;700&display=swap" rel="stylesheet">


	<link rel="stylesheet" href="fonts/icomoon/style.css">
	<link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

	<link rel="stylesheet" href="~/Assets/css/tiny-slider.css">
	<link rel="stylesheet" href="~/Assets/css/aos.css">
	<link rel="stylesheet" href="~/Assets/css/glightbox.min.css">
	<link rel="stylesheet" href="~/Assets/css/style.css">

	<link rel="stylesheet" href="~/Assets/css/flatpickr.min.css">


	<title>Book Store</title>
</head>

<body>

	<div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close">
				<span class="icofont-close js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>

	<nav class="site-nav">
		<div class="container">
			<div class="menu-bg-wrap">
				<div class="site-navigation">
					<div class="row g-0 align-items-center">
						<div class="col-2">
							<a asp-controller="Home" asp-action="Index" class="logo m-0 float-start">Book Store<span class="text-primary">.</span></a>
						</div>
						<div class="col-6 text-center">
							<form action="#" class="search-form d-inline-block d-lg-none">
								<input type="text" class="form-control" placeholder="Search...">
								<i class="bi bi-search"></i>
							</form>

							<ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu mx-auto">
								<li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
								<li><a asp-controller="Blog" asp-action="Index">Blog</a></li>
								<li><a asp-controller="PublicBookAPI" asp-action="Index">Explore</a></li>
								<li><a asp-controller="Cart" asp-action="Index">Cart <i class="bi bi-basket3-fill"></i></a></li>
							</ul>
						</div>
						<div class="col-2 text-end">
							<a  class="burger ms-auto float-end site-menu-toggle js-menu-toggle d-inline-block d-lg-none light">
								<span></span>
							</a>
							<form action="#" class="search-form d-none d-lg-inline-block">
								<input type="text" class="form-control" placeholder="Search...">
								<span class="bi-search"></span>
							</form>
						</div>
						<div class="col-2 text-end">
							<div class="dropdown">
								<a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
									Account  <i class="bi bi-person-circle"></i>
								</a>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
									@if (User.Identity?.IsAuthenticated ?? false )
									{
										<li><p class="dropdown-item">Xin Chào @User.Identity.Name</p></li>
										<li><a asp-controller="Account" asp-action="Logout" asp-route-returnUrl="@Context.Request.Path" class="dropdown-item">Đăng Xuất</a></li>

									}
									else
									{
										<li><a asp-controller="Account" asp-action="SignIn" asp-route-returnUrl="@Context.Request.Path" class="dropdown-item">Đăng nhập</a></li>
										<li><a asp-controller="Account" asp-action="Register" class="dropdown-item">Đăng ký</a></li>
									}
									<li><a asp-area="Admin" asp-controller="Home" asp-action="Index" asp-route-returnUrl="@Context.Request.Path" class="dropdown-item">Administration</a></li>

								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<!-- Start retroy layout blog posts -->
	
	@RenderBody()

	@Html.Partial("_FooterPartial")
    <!-- Preloader -->


    <script src="~/Assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/Assets/js/tiny-slider.js"></script>

    <script src="~/Assets/js/flatpickr.min.js"></script>


    <script src="~/Assets/js/aos.js"></script>
    <script src="~/Assets/js/glightbox.min.js"></script>
    <script src="~/Assets/js/navbar.js"></script>
    <script src="~/Assets/js/counter.js"></script>
    <script src="~/Assets/js/custom.js"></script>

    
  </body>
  </html>

Book_Store/Views/Shared/_SidebarPartial.cshtml
<div class="container p-3 d-flex">

    <div class="col-2 m-3">
        <ul class="list-group">
            <li class="list-group-item fw-bold"><h3>Categories</h3></li>
            <li class="list-group-item"><a asp-controller="Topics" asp-action="Index">Chủ Đề</a></li>
            <li class="list-group-item"><a asp-controller="Books" asp-action="Index">Sách</a></li>
            <li class="list-group-item"><a asp-controller="Publishers" asp-action="Index">NXB</a></li>
            <li class="list-group-item"><a asp-controller="Books" asp-action="ShowBookApi">Book API</a></li>
        </ul>
    </div>